### ISSUE TITLE
ModuleNotFoundError: No module named 'creds'

### ISSUE THREAD

**Issue by BlackMage2** [keisentraut/python-comdirect-api#10]
Hello,

i can't run bin/get_account_balances_and_transactions.py .

i get ever the error:
`Traceback (most recent call last):
  File "/home/user/Development/python-comdirect-api/bin/get_account_balances_and_transactions.py", line 10, in <module>
    from creds import user, password, client_id, client_secret
ModuleNotFoundError: No module named 'creds'`

i had executed
`python setup.py sdist
pip install dist/comdirect_api-0.1.tar.gz`
as described

but that returned only
```
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'pip'
```

but i have executed

`pip3 install dist/comdirect_api-0.1.tar.gz`

that returned

```
Defaulting to user installation because normal site-packages is not writeable
Processing ./dist/comdirect_api-0.1.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from comdirect-api==0.1) (2.25.1)
Requirement already satisfied: pillow in /usr/lib/python3/dist-packages (from comdirect-api==0.1) (9.0.1)
Requirement already satisfied: datetime in /home/user/.local/lib/python3.10/site-packages (from comdirect-api==0.1) (5.2)
Requirement already satisfied: uuid in /home/user/.local/lib/python3.10/site-packages (from comdirect-api==0.1) (1.30)
Requirement already satisfied: zope.interface in /home/user/.local/lib/python3.10/site-packages (from datetime->comdirect-api==0.1) (6.0)
Requirement already satisfied: pytz in /usr/lib/python3/dist-packages (from datetime->comdirect-api==0.1) (2022.1)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from zope.interface->datetime->comdirect-api==0.1) (59.6.0)
Building wheels for collected packages: comdirect-api
  Building wheel for comdirect-api (pyproject.toml) ... done
  Created wheel for comdirect-api: filename=comdirect_api-0.1-py3-none-any.whl size=20902 sha256=64db54674eb0b8f33b0f5898ef67d4a5620238df235612fa971ae24c67c62f83
  Stored in directory: /home/user/.cache/pip/wheels/71/1a/34/bf2ab3a5787b83730600d94df322d4cd5e4de96350435d8351
Successfully built comdirect-api
Installing collected packages: comdirect-api
  Attempting uninstall: comdirect-api
    Found existing installation: comdirect-api 0.1
    Uninstalling comdirect-api-0.1:
      Successfully uninstalled comdirect-api-0.1
Successfully installed comdirect-api-0.1
```

**Comment by keisentraut** [comment]
> i had executed
> python setup.py sdist pip install dist/comdirect_api-0.1.tar.gz
> as described

This should be two commands, see README.md. But seems you already installed it nevertheless.

>api/bin/get_account_balances_and_transactions.py", line 10, in <module> from creds import user, password, client_id, >client_secret ModuleNotFoundError: No module named 'creds'

You are supposed to put your credentials in the a seperate file, see comment here: https://github.com/keisentraut/python-comdirect-api/blob/8e9f5cda2e47c5fff45ac6441e7b71e99121a51c/bin/download_all_documents.py#L7
Alternatively, you can develop your own Python application with the API package - the "download_all_documents.py" script is just an example how to get started.

This being said - I don't know if my stuff still works, have not tested it for >1 year. My main usecase for this toy project is gone as comdirect let's you know finally download more than one document at the same time... If you need to make any changes, feel free to submit a pull request.

**Comment by BlackMage2** [comment]
ok, thanks. would you test it again?
