### ISSUE TITLE
Refactor folder structure into library format

### ISSUE THREAD

**Issue by keisentraut** [keisentraut/python-comdirect-api#4]
The plans for this are to create an actual Python module. Therefore, the complete folder structure needs to be changed to something like [https://realpython.com/python-application-layouts/](this).
Other developers can then write own scripts.

However, the typical user does not want to write custom Python applications.
For him/her, we will create a `bin/` folder with scripts which do all the "most wanted" stuff like:

- downloading the inbox
- getting an excel with all transactions
- getting an excel with all depot transactions

**Comment by sebanger** [comment]
I agree. I also thought about it. Better to do it early in the project.

**Comment by keisentraut** [comment]
I just noticed that I accidentially pushed to the master branch yesterday night. I had created a branch, but did not checkout to it and then pushed it to github. Sry for that, I hope I will finish the refactoring this weekend.

**Comment by keisentraut** [comment]
I consider this done with the latest commits, therefore I'm closing this issue now it now.
